#@data/values-schema
---
cpu: "100m"
#@schema/type any=True
envs: []
image: ""
initMetadata: #@ True
memory: "100Mi"
serviceId: ""
targetPort: 80
virtualInstanceId: ""
lfrdevDomain: "lfr.dev"
rootCA: ""
schedule: "* * * * *"