#@data/values-schema
---
cpu: "500m"
#@schema/type any=True
envs: []
debugPort: 8001
image: ""
dxpMetadata: #@ True
initMetadata: #@ False
memory: "512Mi"
serviceId: ""
targetPort: 80
virtualInstanceId: ""
lfrdevDomain: "lfr.dev"