logging:
    level:
        com.liferay.couponpdf.service: DEBUG
        org.springframework.cloud: DEBUG
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
server:
    port: 80
spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.configtree
  config:
    import: "configtree:/etc/liferay/lxc/*/"